apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-todo
    tier: db
  name: node-todo-mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: node-todo
    tier: db