kind: Deployment
apiVersion: apps/v1
metadata:
  name: node-todo-mongodb  # Name of the deployment
  labels:
    app: node-todo  # Labels for the deployment
    tier: db
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: node-todo  # Match labels for selecting the pods
      tier: db
  template:
    metadata:
      labels:
        app: node-todo  # Labels for the pod
        tier: db
    spec:
      containers:  # Main containers
        - name: mongo
          image: mongo:4  # Image for the container
          resources:
            requests:  # Resource requests for the container
              memory: "64Mi"
              cpu: "250m"
            limits:  # Resource limits for the container
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017  # Port to expose on the container
