apiVersion: v1
kind: Service
metadata:
  name: node-todo-service
  labels:
    app: node-todo-service
spec:
  type: LoadBalancer
  selector:
    app: node-todo
  ports:
  - port: 8080
    targetPort: 8080